clean_hostname: bettley
mac_address: d8:3a:dd:89:c1:0b
ipv4_address: 10.4.0.11
prompt:
  colors:
    primary: 220
    secondary: 18
    tertiary: 94
  emoji: ğŸ
host_index: 1
# Kubespray
ansible_host: "{{ ipv4_address }}"
