clean_hostname: dalt
mac_address: d8:3a:dd:8a:7e:9a
ipv4_address: 10.4.0.13
prompt:
  colors:
    primary: 127
    secondary: 184
    tertiary: 22
  emoji: ğŸ‹
host_index: 3
# Kubespray
ansible_host: "{{ ipv4_address }}"
