clean_hostname: jast
mac_address: d8:3a:dd:89:f0:4b
ipv4_address: 10.4.0.19
prompt:
  colors:
    primary: 11
    secondary: 58
    tertiary: 145
  emoji: ğŸ¦
host_index: 9
# Kubespray
ansible_host: "{{ ipv4_address }}"
